
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Toaster from "./toaster";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Bluecom Email Sender",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
      <Toaster position="top-center" expand={true} richColors />
  	{children}
			</body>
		</html>
	);
}
